sudo: true
language: node_js
node_js:
- '7.6.0'
cache:
  yarn: false
  directories:
    - node_modules
env:
  global:
  # heroku-related commands
before_deploy:
  - npm run build
deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  skip_cleanup: true
  on:
    branch: master